[package]
name = "downloading"
version = "0.0.1"
edition = "2021"
license = "MIT OR Apache-2.0"
keywords = ["download", "downloader", "youtube"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.10.0"
reqwest = "0.12.2"
rusty_ytdl =  {features = ["blocking"], version = "0.7.1"}
serde_json = "1.0.115"
tokio = {features = ["full"], version =  "1.37.0"}
url = "2.5.0"
