[package]
name = "rusty_dl"
version = "0.0.1"
edition = "2021"
license = "MIT OR Apache-2.0"
keywords = ["download", "downloader", "youtube", "twitter"]
description = "A crate for downloading youtube videos, twitter medias (videos, images, gif) from tweets and files on the web."
readme = "README.md"
repository = "https://github.com/DevYatsu/RustyDL"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.30"
percent-encoding = "2.3.1"
rayon = "1.10.0"
regex = "1.10.4"
reqwest = {features = ["multipart"], version = "0.12.2"}
rusty_ytdl =  {features = ["blocking", "ffmpeg"], version = "0.7.1"}
serde = {version = "1.0.197", features = ["derive"]}
serde_json = "1.0.115"
serde_urlencoded = "0.7.1"
tokio = {features = ["full"], version =  "1.37.0"}
url = "2.5.0"
